// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8515837e-0e15-4208-ad2c-dd649c5f4ecd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yXTPQVjLT",
    "aws_user_pools_web_client_id": "1hr7j8g1fmpv3ela2l5uok26am",
    "oauth": {},
    "aws_mobile_analytics_app_id": "f55b027d748a459fbc1648e4b9df124b",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ukqo7pupqrgyrghukun32vb7em.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
