// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.	

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0be40321-fbd2-47e2-b8e5-9ec423b7fc18",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xVwarzjuL",
    "aws_user_pools_web_client_id": "28uvvji2ts3g1pmh1nmfhel34r",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4eet4ctjyrf3znhqf2he6imkh4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;	
