// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3867a42d-7540-4be3-9ed2-f75984a28815",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AkNe7bah5",
    "aws_user_pools_web_client_id": "7kmpr4e5fclkd89bs14d1eogq2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7lp2yyud5zfx7o6ugiucyt3xxa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;